[workspace]
members = [
  "engine/core",
  "engine_macros",
  "engine_py",
  "engine_lua",
  "engine_wasm",
  "engine/tools/schema_validator",
  "plugins/rust_test_plugin",
  "xtask",
  "engine/tools/codegen",
]
resolver = "3"
