[package]
name = "engine_core"
version = "0.1.0"
edition = "2024"

[dependencies]
hecs = "0.10"
mlua = { version = "0.9", features = ["luajit", "serialize"] }
serde = { version = "1.0", features = ["derive"] }
schemars = { version = "0.8", features = ["derive"] }
schemars_derive = "0.8"
serde_json = "1.0.140"
bson = "2.14.0"
semver = { version = "1.0.26", features = ["serde"] }
thiserror = "2.0.12"
engine_macros = { path = "../../engine_macros" }

[dev-dependencies]
rstest = "0.18"
mockall = "0.12"

[[bin]]
name = "mge-cli"
path = "src/bin/mge_cli.rs"
