[package]
name = "schema_validator"
version = "0.1.0"
edition = "2024"

[dependencies]
serde_json = "1"
clap = { version = "4", features = ["derive"] }

[[bin]]
name = "schema_validator"
path = "src/main.rs"
