local id = spawn_entity()
set_component(id, "Position", { x = 0.1, y = 2.2 })
local pos = get_component(id, "Position")
print("From file: pos.x=" .. tostring(pos.x) .. " pos.y=" .. tostring(pos.y))
print_positions()
move_all(1.0, 0.0)
print_positions()
