name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install LuaJIT and pkg-config
        run: sudo apt-get update && sudo apt-get install -y libluajit-5.1-dev pkg-config && sudo apt-get clean

      - uses: moonrepo/setup-rust@v1
        with:
          components: rustfmt, clippy

      - name: Lint (rustfmt)
        run: cargo fmt --all --check

      - name: Clippy
        run: |
          export PKG_CONFIG_PATH=/usr/lib/x86_64-linux-gnu/pkgconfig
          cargo clippy --all-targets --all-features -- -D warnings

      - name: Clean up Rust build artifacts
        run: cargo clean

  test-rust:
    runs-on: ubuntu-latest
    needs: [lint]
    steps:
      - uses: actions/checkout@v4

      - name: Install LuaJIT and pkg-config
        run: sudo apt-get update && sudo apt-get install -y libluajit-5.1-dev pkg-config && sudo apt-get clean

      - uses: moonrepo/setup-rust@v1

      - name: Cache cargo registry and git
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-registry-

      - name: Add wasm32-unknown-unknown target
        run: rustup target add wasm32-unknown-unknown

      - name: Build all plugins and WASM test modules (Rust, C, WASM)
        run: cargo run -p xtask -- build-all

      - name: Build
        run: |
          export PKG_CONFIG_PATH=/usr/lib/x86_64-linux-gnu/pkgconfig
          cargo build --all

      - name: Test (with plugins)
        run: |
          export PKG_CONFIG_PATH=/usr/lib/x86_64-linux-gnu/pkgconfig
          export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$(pwd)/plugins
          cargo test --all

      - name: Clean up Rust build artifacts
        run: cargo clean

  test-lua:
    runs-on: ubuntu-latest
    needs: test-rust
    steps:
      - uses: actions/checkout@v4

      - name: Install LuaJIT and pkg-config
        run: sudo apt-get update && sudo apt-get install -y libluajit-5.1-dev pkg-config && sudo apt-get clean

      - name: Install Lua
        run: sudo apt-get update && sudo apt-get install -y lua5.1 && sudo apt-get clean

      - name: Lua Tests
        run: |
          export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$(pwd)/plugins
          ./run_lua_tests.sh

  test-python:
    runs-on: ubuntu-latest
    needs: test-rust
    steps:
      - uses: actions/checkout@v4

      - name: Install LuaJIT and pkg-config
        run: sudo apt-get update && sudo apt-get install -y libluajit-5.1-dev pkg-config && sudo apt-get clean

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Create and activate virtualenv, install Python deps
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install --upgrade pip
          pip install maturin pytest

      - name: Build and test Python bindings
        run: |
          source .venv/bin/activate
          cd engine_py
          export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$(pwd)/../plugins
          export PKG_CONFIG_PATH=/usr/lib/x86_64-linux-gnu/pkgconfig${PKG_CONFIG_PATH:+:$PKG_CONFIG_PATH}
          maturin develop
          pytest

      - name: Clean up Python venv
        run: rm -rf .venv
