name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: moonrepo/setup-rust@v1
        with:
          components: rustfmt, clippy

      - name: Install LuaJIT and pkg-config
        run: sudo apt-get update && sudo apt-get install -y libluajit-5.1-dev pkg-config && sudo apt-get clean

      - name: Lint (rustfmt)
        run: cargo fmt --all --check

      - name: Clippy
        run: |
          export PKG_CONFIG_PATH=/usr/lib/x86_64-linux-gnu/pkgconfig
          cargo clippy --all-targets --all-features -- -D warnings

      - name: Clean up Rust build artifacts
        run: cargo clean

  validate-schema:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: moonrepo/setup-rust@v1

      - name: Validate schemas (xtask via Makefile)
        run: cargo run --bin schema_validator --release -- engine/assets/schemas

  build-c-plugins:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install build-essential
        run: sudo apt-get update && sudo apt-get install -y build-essential && sudo apt-get clean

      - name: Build all C plugins (xtask via Makefile)
        run: cargo run -p xtask -- build-c-plugins

      - name: Upload C plugins
        uses: actions/upload-artifact@v4
        with:
          name: c-plugins
          path: plugins/*.so

  build-wasm-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: moonrepo/setup-rust@v1
        with:
          targets: wasm32-unknown-unknown

      - name: Build WASM test modules (xtask via Makefile)
        run: cargo run -p xtask -- build-wasm-tests

      - name: Upload WASM test artifacts
        uses: actions/upload-artifact@v4
        with:
          name: wasm-tests
          path: engine_wasm/wasm_tests/**/*.wasm

  build-all:
    runs-on: ubuntu-latest
    needs: [validate-schema, build-c-plugins, build-wasm-tests]
    steps:
      - uses: actions/checkout@v4

      - uses: moonrepo/setup-rust@v1

      - name: Install LuaJIT and pkg-config
        run: sudo apt-get update && sudo apt-get install -y libluajit-5.1-dev pkg-config && sudo apt-get clean

      - name: Download C plugins
        uses: actions/download-artifact@v4
        with:
          name: c-plugins
          path: plugins

      - name: Download WASM test artifacts
        uses: actions/download-artifact@v4
        with:
          name: wasm-tests
          path: engine/wasm_tests

      - name: Build all (xtask via Makefile)
        run: cargo run -p xtask -- build-all

      - name: Clean up Rust build artifacts
        run: cargo clean

  test-rust:
    runs-on: ubuntu-latest
    needs: build-all
    steps:
      - uses: actions/checkout@v4

      - uses: moonrepo/setup-rust@v1

      - name: Install LuaJIT and pkg-config
        run: sudo apt-get update && sudo apt-get install -y libluajit-5.1-dev pkg-config && sudo apt-get clean

      - name: Download C plugins
        uses: actions/download-artifact@v4
        with:
          name: c-plugins
          path: plugins

      - name: Download WASM test artifacts
        uses: actions/download-artifact@v4
        with:
          name: wasm-tests
          path: engine/wasm_tests

      - name: Test Rust (xtask via Makefile)
        run: |
          export PKG_CONFIG_PATH=/usr/lib/x86_64-linux-gnu/pkgconfig
          export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$(pwd)/plugins
          cargo run -p xtask -- build-all
          cargo test --all

      - name: Clean up Rust build artifacts
        run: cargo clean

  test-lua:
    runs-on: ubuntu-latest
    needs: build-c-plugins
    steps:
      - uses: actions/checkout@v4

      - name: Download C plugins
        uses: actions/download-artifact@v4
        with:
          name: c-plugins
          path: plugins

      - name: Install LuaJIT and pkg-config
        run: sudo apt-get update && sudo apt-get install -y libluajit-5.1-dev pkg-config && sudo apt-get clean

      - name: Install Lua
        run: sudo apt-get update && sudo apt-get install -y lua5.1 && sudo apt-get clean

      - name: Lua tests (xtask via Makefile)
        run: ./run_lua_tests.sh

  test-python:
    runs-on: ubuntu-latest
    needs: build-c-plugins
    steps:
      - uses: actions/checkout@v4

      - name: Download C plugins
        uses: actions/download-artifact@v4
        with:
          name: c-plugins
          path: plugins

      - name: Install LuaJIT and pkg-config
        run: sudo apt-get update && sudo apt-get install -y libluajit-5.1-dev pkg-config && sudo apt-get clean

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Create and activate virtualenv, install Python deps
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install --upgrade pip
          pip install maturin pytest

      - name: Build and test Python bindings
        run: |
          source .venv/bin/activate
          cd engine_py
          export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$(pwd)/../plugins
          export PKG_CONFIG_PATH=/usr/lib/x86_64-linux-gnu/pkgconfig${PKG_CONFIG_PATH:+:$PKG_CONFIG_PATH}
          maturin develop
          pytest

      - name: Clean up Python venv
        run: rm -rf .venv
