name: CI

on:
  pull_request:
    branches: [main]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: moonrepo/setup-rust@v1
        with:
          components: rustfmt, clippy
      - name: Install LuaJIT
        run: sudo apt-get update && sudo apt-get install -y libluajit-5.1-dev
      - name: Lint
        run: cargo fmt --all --check
      - name: Clippy
        run: cargo clippy --all-targets --all-features -- -D warnings
      - name: Build C test plugin
        run: |
          gcc -shared -fPIC -o plugins/libtest_plugin.so plugins/test_plugin.c
      - name: Test
        run: cargo test --all
